/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as MesInfosRouteImport } from './routes/mes-infos'
import { Route as MesConsommationsRouteImport } from './routes/mes-consommations'
import { Route as FilialesRouteImport } from './routes/filiales'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollaborateursRouteImport } from './routes/collaborateurs'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingTokenRouteImport } from './routes/onboarding.$token'
import { Route as DashboardStatistiquesRouteImport } from './routes/dashboard/statistiques'
import { Route as DashboardReglagesRouteImport } from './routes/dashboard/reglages'
import { Route as DashboardMesInfosRouteImport } from './routes/dashboard/mes-infos'
import { Route as DashboardMesConsommationsRouteImport } from './routes/dashboard/mes-consommations'
import { Route as DashboardListesRouteImport } from './routes/dashboard/listes'
import { Route as DashboardAdministrationRouteImport } from './routes/dashboard/administration'
import { Route as DashboardListesVehiculesRouteImport } from './routes/dashboard/listes/vehicules'
import { Route as DashboardListesSitesRouteImport } from './routes/dashboard/listes/sites'
import { Route as DashboardListesFilialesRouteImport } from './routes/dashboard/listes/filiales'
import { Route as DashboardListesCollaborateursRouteImport } from './routes/dashboard/listes/collaborateurs'
import { Route as DashboardCollaborateurIdRouteImport } from './routes/dashboard/collaborateur/$id'
import { Route as DashboardListesEntreprisesIndexRouteImport } from './routes/dashboard/listes/entreprises/index'
import { Route as DashboardListesVehiculesVehiculeIdRouteImport } from './routes/dashboard/listes/vehicules.$vehiculeId'
import { Route as DashboardListesEntreprisesIdRouteImport } from './routes/dashboard/listes/entreprises/$id'

const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const MesInfosRoute = MesInfosRouteImport.update({
  id: '/mes-infos',
  path: '/mes-infos',
  getParentRoute: () => rootRouteImport,
} as any)
const MesConsommationsRoute = MesConsommationsRouteImport.update({
  id: '/mes-consommations',
  path: '/mes-consommations',
  getParentRoute: () => rootRouteImport,
} as any)
const FilialesRoute = FilialesRouteImport.update({
  id: '/filiales',
  path: '/filiales',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateursRoute = CollaborateursRouteImport.update({
  id: '/collaborateurs',
  path: '/collaborateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingTokenRoute = OnboardingTokenRouteImport.update({
  id: '/onboarding/$token',
  path: '/onboarding/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatistiquesRoute = DashboardStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReglagesRoute = DashboardReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMesInfosRoute = DashboardMesInfosRouteImport.update({
  id: '/mes-infos',
  path: '/mes-infos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMesConsommationsRoute =
  DashboardMesConsommationsRouteImport.update({
    id: '/mes-consommations',
    path: '/mes-consommations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardListesRoute = DashboardListesRouteImport.update({
  id: '/listes',
  path: '/listes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdministrationRoute = DashboardAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListesVehiculesRoute =
  DashboardListesVehiculesRouteImport.update({
    id: '/vehicules',
    path: '/vehicules',
    getParentRoute: () => DashboardListesRoute,
  } as any)
const DashboardListesSitesRoute = DashboardListesSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => DashboardListesRoute,
} as any)
const DashboardListesFilialesRoute = DashboardListesFilialesRouteImport.update({
  id: '/filiales',
  path: '/filiales',
  getParentRoute: () => DashboardListesRoute,
} as any)
const DashboardListesCollaborateursRoute =
  DashboardListesCollaborateursRouteImport.update({
    id: '/collaborateurs',
    path: '/collaborateurs',
    getParentRoute: () => DashboardListesRoute,
  } as any)
const DashboardCollaborateurIdRoute =
  DashboardCollaborateurIdRouteImport.update({
    id: '/collaborateur/$id',
    path: '/collaborateur/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardListesEntreprisesIndexRoute =
  DashboardListesEntreprisesIndexRouteImport.update({
    id: '/entreprises/',
    path: '/entreprises/',
    getParentRoute: () => DashboardListesRoute,
  } as any)
const DashboardListesVehiculesVehiculeIdRoute =
  DashboardListesVehiculesVehiculeIdRouteImport.update({
    id: '/$vehiculeId',
    path: '/$vehiculeId',
    getParentRoute: () => DashboardListesVehiculesRoute,
  } as any)
const DashboardListesEntreprisesIdRoute =
  DashboardListesEntreprisesIdRouteImport.update({
    id: '/entreprises/$id',
    path: '/entreprises/$id',
    getParentRoute: () => DashboardListesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entreprises': typeof EntreprisesRoute
  '/filiales': typeof FilialesRoute
  '/mes-consommations': typeof MesConsommationsRoute
  '/mes-infos': typeof MesInfosRoute
  '/reglages': typeof ReglagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sites': typeof SitesRoute
  '/statistiques': typeof StatistiquesRoute
  '/vehicules': typeof VehiculesRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/listes': typeof DashboardListesRouteWithChildren
  '/dashboard/mes-consommations': typeof DashboardMesConsommationsRoute
  '/dashboard/mes-infos': typeof DashboardMesInfosRoute
  '/dashboard/reglages': typeof DashboardReglagesRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collaborateur/$id': typeof DashboardCollaborateurIdRoute
  '/dashboard/listes/collaborateurs': typeof DashboardListesCollaborateursRoute
  '/dashboard/listes/filiales': typeof DashboardListesFilialesRoute
  '/dashboard/listes/sites': typeof DashboardListesSitesRoute
  '/dashboard/listes/vehicules': typeof DashboardListesVehiculesRouteWithChildren
  '/dashboard/listes/entreprises/$id': typeof DashboardListesEntreprisesIdRoute
  '/dashboard/listes/vehicules/$vehiculeId': typeof DashboardListesVehiculesVehiculeIdRoute
  '/dashboard/listes/entreprises/': typeof DashboardListesEntreprisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/entreprises': typeof EntreprisesRoute
  '/filiales': typeof FilialesRoute
  '/mes-consommations': typeof MesConsommationsRoute
  '/mes-infos': typeof MesInfosRoute
  '/reglages': typeof ReglagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sites': typeof SitesRoute
  '/statistiques': typeof StatistiquesRoute
  '/vehicules': typeof VehiculesRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/listes': typeof DashboardListesRouteWithChildren
  '/dashboard/mes-consommations': typeof DashboardMesConsommationsRoute
  '/dashboard/mes-infos': typeof DashboardMesInfosRoute
  '/dashboard/reglages': typeof DashboardReglagesRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/collaborateur/$id': typeof DashboardCollaborateurIdRoute
  '/dashboard/listes/collaborateurs': typeof DashboardListesCollaborateursRoute
  '/dashboard/listes/filiales': typeof DashboardListesFilialesRoute
  '/dashboard/listes/sites': typeof DashboardListesSitesRoute
  '/dashboard/listes/vehicules': typeof DashboardListesVehiculesRouteWithChildren
  '/dashboard/listes/entreprises/$id': typeof DashboardListesEntreprisesIdRoute
  '/dashboard/listes/vehicules/$vehiculeId': typeof DashboardListesVehiculesVehiculeIdRoute
  '/dashboard/listes/entreprises': typeof DashboardListesEntreprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entreprises': typeof EntreprisesRoute
  '/filiales': typeof FilialesRoute
  '/mes-consommations': typeof MesConsommationsRoute
  '/mes-infos': typeof MesInfosRoute
  '/reglages': typeof ReglagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sites': typeof SitesRoute
  '/statistiques': typeof StatistiquesRoute
  '/vehicules': typeof VehiculesRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/listes': typeof DashboardListesRouteWithChildren
  '/dashboard/mes-consommations': typeof DashboardMesConsommationsRoute
  '/dashboard/mes-infos': typeof DashboardMesInfosRoute
  '/dashboard/reglages': typeof DashboardReglagesRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collaborateur/$id': typeof DashboardCollaborateurIdRoute
  '/dashboard/listes/collaborateurs': typeof DashboardListesCollaborateursRoute
  '/dashboard/listes/filiales': typeof DashboardListesFilialesRoute
  '/dashboard/listes/sites': typeof DashboardListesSitesRoute
  '/dashboard/listes/vehicules': typeof DashboardListesVehiculesRouteWithChildren
  '/dashboard/listes/entreprises/$id': typeof DashboardListesEntreprisesIdRoute
  '/dashboard/listes/vehicules/$vehiculeId': typeof DashboardListesVehiculesVehiculeIdRoute
  '/dashboard/listes/entreprises/': typeof DashboardListesEntreprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/collaborateurs'
    | '/dashboard'
    | '/entreprises'
    | '/filiales'
    | '/mes-consommations'
    | '/mes-infos'
    | '/reglages'
    | '/reset-password'
    | '/sites'
    | '/statistiques'
    | '/vehicules'
    | '/dashboard/administration'
    | '/dashboard/listes'
    | '/dashboard/mes-consommations'
    | '/dashboard/mes-infos'
    | '/dashboard/reglages'
    | '/dashboard/statistiques'
    | '/onboarding/$token'
    | '/dashboard/'
    | '/dashboard/collaborateur/$id'
    | '/dashboard/listes/collaborateurs'
    | '/dashboard/listes/filiales'
    | '/dashboard/listes/sites'
    | '/dashboard/listes/vehicules'
    | '/dashboard/listes/entreprises/$id'
    | '/dashboard/listes/vehicules/$vehiculeId'
    | '/dashboard/listes/entreprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/collaborateurs'
    | '/entreprises'
    | '/filiales'
    | '/mes-consommations'
    | '/mes-infos'
    | '/reglages'
    | '/reset-password'
    | '/sites'
    | '/statistiques'
    | '/vehicules'
    | '/dashboard/administration'
    | '/dashboard/listes'
    | '/dashboard/mes-consommations'
    | '/dashboard/mes-infos'
    | '/dashboard/reglages'
    | '/dashboard/statistiques'
    | '/onboarding/$token'
    | '/dashboard'
    | '/dashboard/collaborateur/$id'
    | '/dashboard/listes/collaborateurs'
    | '/dashboard/listes/filiales'
    | '/dashboard/listes/sites'
    | '/dashboard/listes/vehicules'
    | '/dashboard/listes/entreprises/$id'
    | '/dashboard/listes/vehicules/$vehiculeId'
    | '/dashboard/listes/entreprises'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/collaborateurs'
    | '/dashboard'
    | '/entreprises'
    | '/filiales'
    | '/mes-consommations'
    | '/mes-infos'
    | '/reglages'
    | '/reset-password'
    | '/sites'
    | '/statistiques'
    | '/vehicules'
    | '/dashboard/administration'
    | '/dashboard/listes'
    | '/dashboard/mes-consommations'
    | '/dashboard/mes-infos'
    | '/dashboard/reglages'
    | '/dashboard/statistiques'
    | '/onboarding/$token'
    | '/dashboard/'
    | '/dashboard/collaborateur/$id'
    | '/dashboard/listes/collaborateurs'
    | '/dashboard/listes/filiales'
    | '/dashboard/listes/sites'
    | '/dashboard/listes/vehicules'
    | '/dashboard/listes/entreprises/$id'
    | '/dashboard/listes/vehicules/$vehiculeId'
    | '/dashboard/listes/entreprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  CollaborateursRoute: typeof CollaborateursRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EntreprisesRoute: typeof EntreprisesRoute
  FilialesRoute: typeof FilialesRoute
  MesConsommationsRoute: typeof MesConsommationsRoute
  MesInfosRoute: typeof MesInfosRoute
  ReglagesRoute: typeof ReglagesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitesRoute: typeof SitesRoute
  StatistiquesRoute: typeof StatistiquesRoute
  VehiculesRoute: typeof VehiculesRoute
  OnboardingTokenRoute: typeof OnboardingTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-infos': {
      id: '/mes-infos'
      path: '/mes-infos'
      fullPath: '/mes-infos'
      preLoaderRoute: typeof MesInfosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-consommations': {
      id: '/mes-consommations'
      path: '/mes-consommations'
      fullPath: '/mes-consommations'
      preLoaderRoute: typeof MesConsommationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiales': {
      id: '/filiales'
      path: '/filiales'
      fullPath: '/filiales'
      preLoaderRoute: typeof FilialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborateurs': {
      id: '/collaborateurs'
      path: '/collaborateurs'
      fullPath: '/collaborateurs'
      preLoaderRoute: typeof CollaborateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/$token': {
      id: '/onboarding/$token'
      path: '/onboarding/$token'
      fullPath: '/onboarding/$token'
      preLoaderRoute: typeof OnboardingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/statistiques': {
      id: '/dashboard/statistiques'
      path: '/statistiques'
      fullPath: '/dashboard/statistiques'
      preLoaderRoute: typeof DashboardStatistiquesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reglages': {
      id: '/dashboard/reglages'
      path: '/reglages'
      fullPath: '/dashboard/reglages'
      preLoaderRoute: typeof DashboardReglagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mes-infos': {
      id: '/dashboard/mes-infos'
      path: '/mes-infos'
      fullPath: '/dashboard/mes-infos'
      preLoaderRoute: typeof DashboardMesInfosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mes-consommations': {
      id: '/dashboard/mes-consommations'
      path: '/mes-consommations'
      fullPath: '/dashboard/mes-consommations'
      preLoaderRoute: typeof DashboardMesConsommationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listes': {
      id: '/dashboard/listes'
      path: '/listes'
      fullPath: '/dashboard/listes'
      preLoaderRoute: typeof DashboardListesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/administration': {
      id: '/dashboard/administration'
      path: '/administration'
      fullPath: '/dashboard/administration'
      preLoaderRoute: typeof DashboardAdministrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listes/vehicules': {
      id: '/dashboard/listes/vehicules'
      path: '/vehicules'
      fullPath: '/dashboard/listes/vehicules'
      preLoaderRoute: typeof DashboardListesVehiculesRouteImport
      parentRoute: typeof DashboardListesRoute
    }
    '/dashboard/listes/sites': {
      id: '/dashboard/listes/sites'
      path: '/sites'
      fullPath: '/dashboard/listes/sites'
      preLoaderRoute: typeof DashboardListesSitesRouteImport
      parentRoute: typeof DashboardListesRoute
    }
    '/dashboard/listes/filiales': {
      id: '/dashboard/listes/filiales'
      path: '/filiales'
      fullPath: '/dashboard/listes/filiales'
      preLoaderRoute: typeof DashboardListesFilialesRouteImport
      parentRoute: typeof DashboardListesRoute
    }
    '/dashboard/listes/collaborateurs': {
      id: '/dashboard/listes/collaborateurs'
      path: '/collaborateurs'
      fullPath: '/dashboard/listes/collaborateurs'
      preLoaderRoute: typeof DashboardListesCollaborateursRouteImport
      parentRoute: typeof DashboardListesRoute
    }
    '/dashboard/collaborateur/$id': {
      id: '/dashboard/collaborateur/$id'
      path: '/collaborateur/$id'
      fullPath: '/dashboard/collaborateur/$id'
      preLoaderRoute: typeof DashboardCollaborateurIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listes/entreprises/': {
      id: '/dashboard/listes/entreprises/'
      path: '/entreprises'
      fullPath: '/dashboard/listes/entreprises/'
      preLoaderRoute: typeof DashboardListesEntreprisesIndexRouteImport
      parentRoute: typeof DashboardListesRoute
    }
    '/dashboard/listes/vehicules/$vehiculeId': {
      id: '/dashboard/listes/vehicules/$vehiculeId'
      path: '/$vehiculeId'
      fullPath: '/dashboard/listes/vehicules/$vehiculeId'
      preLoaderRoute: typeof DashboardListesVehiculesVehiculeIdRouteImport
      parentRoute: typeof DashboardListesVehiculesRoute
    }
    '/dashboard/listes/entreprises/$id': {
      id: '/dashboard/listes/entreprises/$id'
      path: '/entreprises/$id'
      fullPath: '/dashboard/listes/entreprises/$id'
      preLoaderRoute: typeof DashboardListesEntreprisesIdRouteImport
      parentRoute: typeof DashboardListesRoute
    }
  }
}

interface DashboardListesVehiculesRouteChildren {
  DashboardListesVehiculesVehiculeIdRoute: typeof DashboardListesVehiculesVehiculeIdRoute
}

const DashboardListesVehiculesRouteChildren: DashboardListesVehiculesRouteChildren =
  {
    DashboardListesVehiculesVehiculeIdRoute:
      DashboardListesVehiculesVehiculeIdRoute,
  }

const DashboardListesVehiculesRouteWithChildren =
  DashboardListesVehiculesRoute._addFileChildren(
    DashboardListesVehiculesRouteChildren,
  )

interface DashboardListesRouteChildren {
  DashboardListesCollaborateursRoute: typeof DashboardListesCollaborateursRoute
  DashboardListesFilialesRoute: typeof DashboardListesFilialesRoute
  DashboardListesSitesRoute: typeof DashboardListesSitesRoute
  DashboardListesVehiculesRoute: typeof DashboardListesVehiculesRouteWithChildren
  DashboardListesEntreprisesIdRoute: typeof DashboardListesEntreprisesIdRoute
  DashboardListesEntreprisesIndexRoute: typeof DashboardListesEntreprisesIndexRoute
}

const DashboardListesRouteChildren: DashboardListesRouteChildren = {
  DashboardListesCollaborateursRoute: DashboardListesCollaborateursRoute,
  DashboardListesFilialesRoute: DashboardListesFilialesRoute,
  DashboardListesSitesRoute: DashboardListesSitesRoute,
  DashboardListesVehiculesRoute: DashboardListesVehiculesRouteWithChildren,
  DashboardListesEntreprisesIdRoute: DashboardListesEntreprisesIdRoute,
  DashboardListesEntreprisesIndexRoute: DashboardListesEntreprisesIndexRoute,
}

const DashboardListesRouteWithChildren = DashboardListesRoute._addFileChildren(
  DashboardListesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdministrationRoute: typeof DashboardAdministrationRoute
  DashboardListesRoute: typeof DashboardListesRouteWithChildren
  DashboardMesConsommationsRoute: typeof DashboardMesConsommationsRoute
  DashboardMesInfosRoute: typeof DashboardMesInfosRoute
  DashboardReglagesRoute: typeof DashboardReglagesRoute
  DashboardStatistiquesRoute: typeof DashboardStatistiquesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCollaborateurIdRoute: typeof DashboardCollaborateurIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdministrationRoute: DashboardAdministrationRoute,
  DashboardListesRoute: DashboardListesRouteWithChildren,
  DashboardMesConsommationsRoute: DashboardMesConsommationsRoute,
  DashboardMesInfosRoute: DashboardMesInfosRoute,
  DashboardReglagesRoute: DashboardReglagesRoute,
  DashboardStatistiquesRoute: DashboardStatistiquesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCollaborateurIdRoute: DashboardCollaborateurIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  CollaborateursRoute: CollaborateursRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EntreprisesRoute: EntreprisesRoute,
  FilialesRoute: FilialesRoute,
  MesConsommationsRoute: MesConsommationsRoute,
  MesInfosRoute: MesInfosRoute,
  ReglagesRoute: ReglagesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitesRoute: SitesRoute,
  StatistiquesRoute: StatistiquesRoute,
  VehiculesRoute: VehiculesRoute,
  OnboardingTokenRoute: OnboardingTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
